apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
  labels:
    app: todoapp
spec:
  containers:
  - name: todoapp
    image: lexm7/todoapp:3.0.0
    ports:
    - containerPort: 8000
    livenessProbe:
      httpGet:
        path: /health/liveness
        port: 8000
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /health/readiness
        port: 8000
      initialDelaySeconds: 5
      periodSeconds: 10